package com.habitly.app.ui.theme

import androidx.compose.ui.graphics.Color

val HabitlyPrimaryLight = Color(0xFF2F6F5E)
val HabitlyOnPrimaryLight = Color(0xFFFFFFFF)
val HabitlyPrimaryContainerLight = Color(0xFFCFEEE1)
val HabitlyOnPrimaryContainerLight = Color(0xFF0B3B2E)
val HabitlySecondaryLight = Color(0xFFE8A33D)
val HabitlyOnSecondaryLight = Color(0xFF402D00)
val HabitlySecondaryContainerLight = Color(0xFFFBE3C2)
val HabitlyOnSecondaryContainerLight = Color(0xFF4A2E00)
val HabitlyBackgroundLight = Color(0xFFF1F3F0)
val HabitlyOnBackgroundLight = Color(0xFF1C1E1B)
val HabitlySurfaceLight = Color(0xFFFAFAF8)
val HabitlyOnSurfaceLight = Color(0xFF1C1E1B)
val HabitlySurfaceVariantLight = Color(0xFFE1E4DE)
val HabitlyOnSurfaceVariantLight = Color(0xFF45483F)
val HabitlyOutlineLight = Color(0xFF767A70)
val HabitlyOutlineVariantLight = Color(0xFFC7CBC1)
val HabitlyErrorLight = Color(0xFFBA1A1A)
val HabitlyOnErrorLight = Color(0xFFFFFFFF)
val HabitlyErrorContainerLight = Color(0xFFFFDAD6)
val HabitlyOnErrorContainerLight = Color(0xFF410002)
val HabitlyStreakAccentLight = Color(0xFF8A5A00)

val HabitlyPrimaryDark = Color(0xFF8FD9C4)
val HabitlyOnPrimaryDark = Color(0xFF00382C)
val HabitlyPrimaryContainerDark = Color(0xFF1D4E40)
val HabitlyOnPrimaryContainerDark = Color(0xFFABE8D5)
val HabitlySecondaryDark = Color(0xFFF0C078)
val HabitlyOnSecondaryDark = Color(0xFF452C00)
val HabitlySecondaryContainerDark = Color(0xFF5C3E00)
val HabitlyOnSecondaryContainerDark = Color(0xFFFFDDAE)
val HabitlyBackgroundDark = Color(0xFF14181C)
val HabitlyOnBackgroundDark = Color(0xFFE8ECE9)
val HabitlySurfaceDark = Color(0xFF1E2422)
val HabitlyOnSurfaceDark = Color(0xFFE8ECE9)
val HabitlySurfaceVariantDark = Color(0xFF333B36)
val HabitlyOnSurfaceVariantDark = Color(0xFFC2C9BF)
val HabitlyOutlineDark = Color(0xFF8C9389)
val HabitlyOutlineVariantDark = Color(0xFF43493F)
val HabitlyErrorDark = Color(0xFFFFB4AB)
val HabitlyOnErrorDark = Color(0xFF690005)
val HabitlyErrorContainerDark = Color(0xFF93000A)
val HabitlyOnErrorContainerDark = Color(0xFFFFDAD6)

val HabitlyHeatmapFillLight = Color(0xFF2F6F5E)
val HabitlyHeatmapFillDark = Color(0xFF37876F)
val HabitlyTodayRingFilled = Color(0xFFFFFFFF)
